---
- name: Create RG in Azure
  hosts: localhost
  connection: local
  
  collections:
    - azure.azcollection
  
  tasks:
    - name: Creating resource group
      azure_rm_resourcegroup:
        name: "{{ rg }}"
        location: "{{ location }}"

