---
- name: Create RG in Azure
  hosts: localhost
  connection: local
  
  collections:
    - azure.azcollection
  
  tasks:
    # - set_fact:
    #     test: "{{ tags.split(',')  }}"
    # - debug:
    #     var: test
    # #- fail:
    - name: Creating resource group
      azure_rm_resourcegroup:
        name: "{{ rg }}"
        location: "{{ location }}"
        append_tags: true
        tags: "{{ tags | from_json }}"