---
- name: Create RG in Azure
  hosts: localhost
  connection: local
  
  collections:
    - azure.azcollection
  
  tasks:
    - debug:
        var: tags.splitlines()|from_yaml)

    - name: Creating resource group
      azure_rm_resourcegroup:
        name: "{{ rg }}"
        location: "{{ location }}"
        append_tags: true
        tags: |
          "{{ tags.splitlines()|from_yaml }}"

